version: '2'

services:
  markov:
    build: .
    restart: unless-stopped
    container_name: discord-rmb-bot
    mem_limit: 128m
    environment:
      - DISCORD_ROLE_SOURCE1=1234123412341234
      - DISCORD_ROLE_SOURCE2=1234123412341235
      - DISCORD_ROLE_DEST=1234123412341236
      - DISCORD_SERVER_ID=1234123412341234
      - DISCORD_TOKEN=1234123412341234
    labels:
      - com.centurylinklabs.watchtower.enable=false